 
 
   <!-- Hero Block Section Start -->
   <div class="hero-block section-ptb">
        <div class="container relative">
            <div class="row">
                <div class="col-xs-12 col-sm-10 col-md-6">
                    <div class="hero-text mt-20">
                        <h2 class="mb-25">Qui suis-je ?</h2>                 
                        <p>Je m'appelle Marie Chambaud, j’ai 33 ans et je suis originaire d'Aix-en-Provence.</p>
                        <br>
                        <p>Fortement attirée par les possibilités qu'offrent le web et disposant de plus de 8 ans d'expérience professionnelle dans le domaine, j'ai créé Baudstudio afin de mettre mes connaissances et compétences au service d'entreprises et organisations ambitieuses.</p>
                        <br>
                        <p>J'interviens sur la création d'outils de communication en ligne : site vitrine, e-commerce, application, plateforme en ligne, newsletter, outil interne, réseaux sociaux, en tant que UX/UI Designer et Chef de Projet.</p>
                        <a class="btn" href="/portfolio.php">Découvrez mon portfolio</a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-6 align-center">
                    <div>
                        <img class="img-style-1" src="/assets/img/accueil/marie-chambaud-baudstudio.png" alt="Marie Chambaud, UI UX designer et web designer à Aix-en-Provence">
                    </div>
                </div>
            </div>

            <div class="composant-9"><img src="/assets/img/composants/Composant-9.png"></div>
        </div>
    </div>
    <!-- Hero Block Section End -->

    <!-- Bloc de citation Start -->
    <div class="section-ptb drak-bg">
        <div class="container relative">
            <div class="row">
                <div class="text-center">
                    <h5 class="q-title white-text">Mon proverbe préféré :</h5>
                    <q class="white-text">
                    Recherchez la liberté et vous deviendrez esclave de vos désirs.<br>
                    Recherchez la discipline et vous trouverez la liberté.
                    </q> <br>
                    <cite class="white-text">Koan Zen</cite>
                </div>
            </div>
        </div>
    </div>          
    <!-- Bloc de citation End -->

    <!-- Bloc diplome et compétences Start -->
    <div class="hero-block section-ptb">
        <div class="container relative">
            <div class="row">
                <div class="col-xs-12 col-sm-10 col-md-6">
                    <div class="hero-text mt-20">
                        <h4 class="mb-25">Diplômes</h4> 
                        
                            <ul>
                                <li class="puce">
                                Formation de Développeur / Intégrateur en <br>développement d’application Web <br>
                                <span class="light-italic">3WAcademy (2018)</span>
                                </li>
                            </ul>

                            <br>

                            <ul>
                                <li class="puce">
                                Master II en Marketing et Communication Digitale <br>
                                <span class="light-italic">Idrac Lyon - Sup de Com’ (2014)</span>
                                </li>
                            </ul>

                            <br>

                            <ul>
                                <li class="puce">
                                Licence en économie <br>
                                <span class="light-italic">Université de Perpignan (2011)</span>
                                </li>
                            </ul>

                            <br>

                            

                            <br>


                    </div>
                </div>

                <div class="col-xs-12 col-sm-10 col-md-6">
                    <div class="hero-text mt-20">
                        <h4 class="mb-25">Compétences</h4>                 
                          <ul>
                            <li class="puce"><p>Cette double casquette stratégique + technique ainsi que ma culture numérique me permettent <span class="strong"> de mieux comprendre les enjeux globaux de vos projets</span>.</p></li>
                            <li class="puce"><p>Mes compétences en management transversale me permettront de coordonner au mieux les opérations liées à votre projet dans <span class="strong">un scoop allant de la traduction des besoins utilisateurs en spécifications fonctionnelles jusqu'au recettage et à la mise en production</span>.</p></li>
                            <li class="puce"><p>Passionnée par le design, <span class="strong">je suis spécialisée en UI/UX</span>. Mes clients s'adressent en général à moi pour des missions de chef de projet web et UX designer.</p></li>
                          </ul>  
        
                    </div>
                </div>
            </div>
        </div>
    </div>       
    <!-- Bloc diplome et compétences End -->

    <hr class="hr2">

    <!-- Bloc outils et logiciels Start -->

    <div class="hero-block section-ptb">
        <div class="container relative">
            <div class="row">
            <h4 class="mb-45">Outils et logiciels de design</h4>  
                <div class="flex sm-block">

                    <div class="flex col-sm-4 align-center mt-25">
                        <div class="align-center"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/figma.png" alt="Figma & Figjam logiciel de design"></div>
                            <div class="nom-logiciel">Figma & Figjam</div>
                        </div>
                        
                        <div class="align-center"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/xd.png" alt="Adobe XD logiciel de design"></div>
                            <div class="nom-logiciel">Adobe XD</div>
                        </div>
                    </div>

                    <div class="flex col-sm-4 align-center mt-25">
                        <div class="align-center"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/photoshop.png" alt="Photoshop logiciel de retouche"></div>
                            <div class="nom-logiciel">Photoshop</div>
                        </div>

                        <div class="align-center"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/indesign.png" alt="InDesing logiciel de mise en page"></div>
                            <div class="nom-logiciel">InDesign</div>
                        </div>
                    </div>

                    <div class="flex col-sm-4 align-center mt-25">
                        <div class="align-center"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/illustrator.png" alt="Illustrator logiciel de design"></div>
                            <div class="nom-logiciel">Illustrator</div>
                        </div>

                        <div class="align-center"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/lightroom.png" alt="Lightroom logiciel de retouche photo"></div>
                            <div class="nom-logiciel">Lightroom</div>
                        </div>
                    </div>


                </div>
            </div>  
        </div>
    </div>  

    <!-- Bloc outils et logiciels End -->

    <hr class="hr2">

    <!-- Bloc outils de ticketing Start -->


    <!-- <div class="hero-block section-ptb">
        <div class="container relative">
            <div class="row">
            <h4 class="mb-25">Outils de ticketing</h2>  
                <div class="flex sm-block">

                    <div class="flex col-sm-4 align-left mt-25">
                        <div class="align-center plr-15"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/trello.png" alt="trello outil de ticketing"/></div>
                            <div class="nom-logiciel">Trello</div>
                        </div>

                        <div class="align-center plr-15"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/jira.png" alt="jira atlassian outil de ticketing"/></div>
                            <div class="nom-logiciel">Jira</div>
                        </div>
                    </div>

                </div>
            </div>  
        </div>
    </div>   -->

    <!-- Bloc outils de ticketing End -->

    <hr class="hr2">

    <!-- Bloc test -->

    <div class="hero-block">
        <div class="container relative">

            <div class="row">

                <div class="flex sm-block">

                    <div class="col section-ptb">
                            <h4 class="mb-25">Outils de ticketing</h4>  

                            <div class="flex col-sm-8 align-left mt-25">

                                <div class="align-center plr-15"> 
                                    <div><img class="up-on-hover width-200-px" src="/assets/img/logos/trello.png" alt="trello outil de ticketing"></div>
                                    <div class="nom-logiciel">Trello</div>
                                </div>

                                <div class="align-center plr-15"> 
                                    <div><img class="up-on-hover" src="/assets/img/logos/jira.png" alt="Jira outil de ticketing"></div>
                                    <div class="nom-logiciel">Jira</div>
                                </div>
                            </div>
                    </div>

                    <div class="col-sm-1">
                        <hr class="hr2">
                    </div>

                    <div class="col section-ptb">
                            <h4 class="mb-25">Outils de productivité</h4>  

                            <div class="flex col-sm-8 align-left mt-25">

                                <div class="align-center plr-15"> 
                                    <div><img class="up-on-hover" src="/assets/img/logos/notion.png" alt="notion outil de ticketing"></div>
                                    <div class="nom-logiciel">Notion</div>
                                </div>

                                <div class="align-center plr-15"> 
                                    <div><img class="up-on-hover" src="/assets/img/logos/loop.png" alt="Loop outil de ticketing"></div>
                                    <div class="nom-logiciel">Loop</div>
                                </div>
                            </div>
                    </div>
                </div>   

            </div>

        </div>
    </div>

    
    <!-- end Bloc test-->

    <!-- <hr class="hr2"> -->

    <!-- Bloc outils de productivité et travail collaboratif -->

    <!-- <div class="hero-block section-ptb">
        <div class="container relative">
            <div class="row">
            <h4 class="mb-25">Outils de productivité & travail collaboratif</h2>  
                <div class="flex sm-block">

                    <div class="flex col-sm-4 align-left mt-25">
                        <div class="align-center plr-15"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/notion.png" alt="Notion"/></div>
                            <div class="nom-logiciel">Notion</div>
                        </div>

                        <div class="align-center plr-15"> 
                            <div><img class="up-on-hover" src="/assets/img/logos/loop.png" alt="Loop"/></div>
                            <div class="nom-logiciel">Loop</div>
                        </div>

                    </div>

                </div>
            </div>  
        </div>
    </div>   -->

    <!-- Bloc outils de ticketing End -->




    <hr class="hr2">

    <!-- Bloc technos Start -->

    <div class="hero-block section-ptb">
        <div class="container relative">
        <h4 class="mb-25">Technologies</h4> 
            <div class="row">
                            <div class="col-xs-12 col-sm-10 col-md-6">
                                <div class="hero-text mt-20">

                                    <div>
                                        <div class="nom-logiciel">HTML</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-html" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="90" style="width: 90%"></div>
                                        </div>                     
                                    </div> 

                                    <div>
                                        <div class="nom-logiciel">CSS</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-css" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="90" style="width: 90%"></div>
                                        </div>                     
                                    </div> 

                                    <div>
                                        <div class="nom-logiciel">Javascript</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-js" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100" style="width: 55%"></div>
                                        </div>                     
                                    </div> 

                                    <div>
                                        <div class="nom-logiciel">jQuery</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-jquery" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100" style="width: 55%"></div>
                                        </div>                     
                                    </div> 

                                    <div>
                                        <div class="nom-logiciel">Ajax</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-ajax" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%"></div>
                                        </div>                     
                                    </div> 

                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-10 col-md-6">
                                <div class="hero-text mt-20">

                                    <div>
                                        <div class="nom-logiciel">Angular</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-angular" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 10%"></div>
                                        </div>   
                                    </div> 

                                    <div>
                                        <div class="nom-logiciel">MySQL</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-mysql" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"></div>
                                        </div>                     
                                    </div> 

                                    <div>
                                        <div class="nom-logiciel">PHP</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-php" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"></div>
                                        </div>                     
                                    </div> 

                                    <div>
                                        <div class="nom-logiciel">Symfony</div>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-symfony" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="100" style="width: 3%"></div>
                                        </div>                     
                                    </div> 

                                </div>
                            </div>
            </div>
        </div>
    </div>   

    <!-- Bloc technos End -->