<!-- Footer Section Start -->
	<footer class="footer">
	<div class="composant-2"><img src="/assets/img/composants/Composant-2.png" alt="forme graphique abstraite"></div>
	<div class="composant-3"><img src="/assets/img/composants/Composant-3.png" alt="forme graphique abstraite"></div>
		<div class="footer-widget-area drak-bg ptb-100">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-sm-4 col-md-5 mobi-mb-30">
						<div class="footer-widget about">
							<div class="title mb-20">
								<h4>BAUDSTUDIO</h4>
							</div>
						   <p>Vous avez besoin de visibilité digitale pour votre projet mais vous ne savez pas par ou commencer ?</p>
						   <p class="pt-25"> Nous développons le site internet adapté à vos besoins.</p>
						   
                           <div class="pt-25">
								<p><a href="/controleur/login.php">Connexion au BO</a></p>
						   		<p><a href="/vue/front/game/index.php">Pierre, Feuille ou Ciseaux ?</a></p>
						   </div>
						</div>
					</div>
					<!-- /.Widget end -->
					<div class="col-xs-12 col-sm-4 col-md-4 mobi-mb-30">
						<div class="footer-widget address">
							<div class="title mb-20">
								<h4>Contact</h4>
							</div>
							
							<div>
								<p>
									<span>Email:</span> <a href="mailto:contact@baudstudio.fr">contact[@]baudstudio[.]fr</a>
								</p>

								
									<ul class="pt-25">	
										<li> Aix-en-Provence</li>
										<li>Marseille</li>
										<li> Le Puy en Velay</li>
									</ul>
								
							</div>

						</div>
					</div>
					<!-- /.Widget end -->
					<div class="col-xs-12 col-sm-4 col-md-3">
						<div class="footer-widget social-media">
							<div class="title mb-20">
								<h4>Suivez-nous</h4>
							</div>
							<div class="social-link">
								<ul class="clearfix d-inblock">
									<li><a href="http://www.instagram.com/baudstudio/" target="_blank">Instagram</a></li>
									<li><a href="https://www.facebook.com/baudstudio" target="_blank">Facebook</a></li>
                  <li><a href="https://www.linkedin.com/company/baudstudio/" target="_blank">LinkedIn</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /.Widget end -->
				</div>
			</div>
		</div>
		<!-- /.Widget Area End -->
		<div class="copyright sombre-bg ptb-15">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 text-center">
						<div class="text">
							<p>&copy; 2024 BAUDSTUDIO.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer Section End -->

    <!-- JAVASCRIPT -->
   
	  <!-- jQuery -->
    <script src="/assets/js/vendor/jquery-1.12.4.min.js"></script>
	<!-- Plugins JS -->
	<script src="/assets/js/burger-menu.js"></script>
    <!-- Plugins JS -->
    <script src="/assets/js/plugins.js"></script>
    <!-- main JS -->
	<script src="/assets/js/main.js"></script>
	

</body>

</html>