<div class="service-area style1 section-ptb">
        <div class="container relative">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <div class="section-title pb-80">
                        <h2 class="mb-15">Nos formations</h2>
                        <p>adaptés à vos besoins</p>
                        <hr class="horizontal_line hr_type_2">
                    </div>
                    <div class="bloc-formation align-left">
                        <p><strong>C'est pour bientôt !</strong></p>
                        <p> Vous êtes nouvel entrepreneur ? Budget trop serrer pour sous-traiter toute la création de votre site vitrine ? <strong>Co-créez le avec moi !</strong><br></p>
                        <br>
                        <p>
                        Je vous propose de vous réunir en groupe de 6 à 8 entrepreneurs et de co-créer votre site vitrine de A à Z en 5 jours.<br>
                        Repartez le vendredi à 17 heures avec votre site complet clès en main en ligne ! </p>

                        <p>Intéressé ? Inscrivez-vous à notre newsletter pour être informé des dates de la prochaine session !</p>
                    </div>
                </div>
            </div>

            <div class="composant-formation"><img src="assets/img/composants/Composant-6.png"/></div>

            <div>
            <iframe class="mj-w-res-iframe" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://app.mailjet.com/widget/iframe/4wQJ/FMF" width="100%"></iframe>

<script type="text/javascript" src="https://app.mailjet.com/statics/js/iframeResizer.min.js"></script>
            </div>    

        </div>
    </div>   
    
    <?php 
    //<!-- I INCLUDE CTA SECOND HERE  -->
    include 'cta-second.phtml'; 
    //<!-- =========================== -->
    ?>
