<body>

    <!-- Loading Bar Start -->
    <!-- <div id="loading-wrap">
        <div class="loading-effect"></div>
    </div> -->
    <!-- Loading Bar End -->
    

    <!-- Header Section Start -->
    <header>

            <div class="container flex space-between align-center">
                <a class="navbar-brand" href="/"><img src='/assets/img/logo-baudstudio-design-aix-en-provence.png' alt="Logo de Baudstudio"></a>
                <nav class="nav navbar sticky-top navbar-expand-lg navbar-light">

                        <ul>
                            <li><a class="nav-link active" aria-current="page" href="/">Accueil</a></li>
                            <li><a class="nav-link" href="/vue/front/pages/a-propos.php">A propos</a></li>
                            <li><a class="nav-link" href="/vue/front/pages/portfolio.php">Portfolio</a></li>
                            <li><a class="nav-link" href="/#contact_form">Contact</a></li>
                        </ul>
                    
                </nav>
                <div class="burger-menu">&#9776;</div>
            </div>                            

    </header>
    <!-- Header Space -->
    <!-- Header Section End -->