<!doctype html>

<html class="no-js" lang="fr">

<head>

   <!--       
   
    DIGITAL LOVE & WEB DEVELOPPEMENT - ALL MADE WITH HEART BY BAUDSTUDIO <3 

                      -> -> ->  www.baudstudio.fr  <- <- <-

 ____    _____           ____            ___   ________          ____         ____
|    \  |     | |     | |    \          /   \      |    |     | |    \   |   /    \
|     | |     | |     | |     \        /     \     |    |     | |     \  |  /      \
|____/  |_____| |     | |      \       \____       |    |     | |      \ | /        \
|    \  |     | |     | |      /            \      |    |     | |      / | \        /
|     | |     | |     | |     /              \     |    |     | |     /  |  \      /
|___ /  |     | |_____| |____/         \_____/     |    |_____| | ___/   |   \____/


                    UN PROJET DIGITAL ? CONTACTEZ-NOUS !
                           contact@baudstudio.fr

 -->

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Baudstudio - Création de site internet et gestion de projet web sur aix et marseille ainsi que le puy en velay en auvergne. Nous réalisons vos site vitrine, e-commerce, wordpress, prestashop à prix accessible.">
    <meta name="keywords" content="site internet, site vitrine, e-commerce, wordpress, prestashop, design d'inteface, ui, ux, projet web, Aix-en-Provence, Marseille, le puy en velay, auvergne">
    <meta name="Copyright" content="BaudStudio">
    <meta name="author" content="Marie Chambaud">

    <title>Baudstudio || UI/UX design et création de site internet</title>

    <!-- Mise en place dufavicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- Préload des fonts -->
    <!-- <link rel="preload" as="font"> -->

    <!-- Font Poppins Acier Bat et Abadi Condensed -->
    <link rel="stylesheet" href="https://use.typekit.net/ycz1wdb.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <!-- Twic pics pour l'optimisation du chargement des images -->
    <script async defer src="https://2keja86r.twic.pics/?v1"></script>

    <!-- Bootstrap nouvelle version 5.0.0 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- style css -->
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/styles.css">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!--
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XYEQ72F7FB"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-XYEQ72F7FB');
    </script>
    -->
      
    <!-- reCaptcha pour sécuriser le formulaire de contact et éviter les boots -->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    <!-- Hotjar Tracking Code for www.baudstudio.fr -->
    <!--
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:2345010,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
    --> 

</head>

