<!-- Services Section Start -->
<div id="services" class="service-area style1 section-ptb drak-bg">
        <div class="container relative">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <div class="section-title white pb-80">
                        <h2 class="mb-15">Nos Services</h2>
                        <p>adaptés à vos besoins</p>
                    </div>
                </div>
            </div>

            <div class="composant-1"><img src="assets/img/composants/Composant-1.png"/></div>
            <!-- <div class="composant-6"><img src="assets/img/composants/Composant-6.png"/></div> -->


            <div class="row mb-30">
                <div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
                    <div class="service-box bg-color-1">
                        <i class="icon-heart"></i>
                        <h4>Identité web</h4>
                        <p>Élaborer un Digital Style Guide en adéquation avec votre identité visuelle.</p>
                    </div>
                </div>
                <!-- Single Service End -->
                <div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
                    <div class="service-box bg-color-1">
                        <i class="icon-tools"></i>
                        <h4>UI/UX Design</h4>
                        <p>Une expérience utilisateur moderne, ergonomique, intuitive.</p>
                    </div>
                </div>
                <!-- Single Service End -->
                <div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30">
                    <div class="service-box bg-color-1">
                        <i class="icon-gears"></i>
                        <h4>Web développement</h4>
                        <p>Un code propre, optimisé. <br> Techno utilisées : HTML / CSS / Javascript / MySQL / PHP.</p>
                    </div>
                </div>
                <!-- Single Service End -->
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="service-box bg-color-1">
                        <i class="icon-strategy"></i>
                        <h4>Newsletter</h4>
                        <p>Communiquer par mail avec vos clients (création et gestion des envois).</p>
                    </div>
                </div>
                <!-- Single Service End -->
            </div>
        </div>
    </div>
    <!-- Services Section End -->


    <?php 
    //<!-- I INCLUDE CTA SECOND HERE  -->
    include 'cta-second.phtml'; 
    //<!-- =========================== -->
    ?>