<?php
// session_start();
?>

<div class="white-bg pt-30 pb-120">
  <div class="container">
    <div class="row">

        <p><a href="/" style="color: #f55650;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
        </svg> Retour au site</a></p>

        <form class="backoffice" method="post" action="controleur/new-user.php">

          <h1>s'inscrire</h1>

              <div>
                <p class="errMessage">
                  <?php echo($_GET['errMessage']); ?>
                </p>
              </div>

              <div class="block mtb-10">
                <label class="width100" for="username">Adresse email </label> 
                <input type="email" name="username" id="email" placeholder="Votre adresse email">
              </div>  


              <div class="block mtb-10">
                <label class="width100" for="mdp">Mot de passe </label> 
                <input type="password" name="password" id="password" placeholder="Votre mot de passe">
              </div>
      
          <button class="btn" type="submit" id="submit">S'inscrire</button>

        </form>

      <p class="backoffice" >Vous n'avez pas encore de compte ? <a href="/login.php">S'inscrire</a></p>

    </div>	
  </div>	
</div>
